steps:
  # 1. Constrói a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${COMMIT_SHA}'
      - '.'
    id: 'Build Docker Image'

  # 2. Envia a imagem Docker para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${COMMIT_SHA}'
    id: 'Push to Artifact Registry'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${COMMIT_SHA}'

substitutions:
  _REGION: 'southamerica-east1' # Ajuste para a região do seu Artifact Registry
  _REPOSITORY: 'meu-bot-repo' # Nome do seu repositório no Artifact Registry
  _IMAGE_NAME: 'meu-bot-whatsapp'
  _SERVICE_NAME: 'meu-bot-whatsapp-service'

options:
  logging: CLOUD_LOGGING_ONLY
